### ISSUE TITLE
How to build anki environment?

### ISSUE THREAD

**Issue by PlEaSeH** [glutanimate/anki-addon-builder#15]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of `aab`
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

I know that pyuicc not found pyuicc skipped means that I did not run the anki environment. However, I installed all prerequisites. All that is left is "execute ./run in this repo,
which will build the subcomponents, and start Anki"
Unfortunately, I do not know what that means at all!

**Comment by PlEaSeH** [comment]
Anki Add-on Builder v0.1.4

Copyright (C) 2016-2019  Aristotelis P. (Glutanimate)  <https://glutanimate.com>

This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions; For details please see the LICENSE file.

Getting Git version info...

=== Build task 1/1 ===

--- Building Cloze Overlapper v0.4.0-alpha.0 for anki21/local ---

Cleaning repository...
Exporting Git archive...
Copying licenses...
Copying changelog...
Writing manifest...
Building UI...
Starting UI build tasks for target 'anki21'...
pyuic5 not found. Skipping pyuic5 build.
pyrcc5 not found. Skipping pyrcc5 build.
Done with all UI build tasks.
Packaging add-on...
Package saved as cloze-overlapper-v0.4.0-alpha.0-anki21.ankiaddon

**Comment by PlEaSeH** [comment]
Also, I did do the run file if that was what the text was referring, too. Unfortunately, every time I did the last prompt in the file, it crashed. However, (I don't know if I should have done this) I did sudo apt install. Then, it installed. Afterward, I installed the addon builder and it didn't work displaying pyuic5 not found etc.

**Comment by PlEaSeH** [comment]
Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 490, in handler
  File "aqt\editor.py", line 479, in <lambda>
  File "<C:\Users\cuten\Desktop\Anki\decorator.pyc:decorator-gen-54>", line 2, in _addCards
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\overlapper.py", line 203, in updateNote
    note.flush()
  File "lib\site-packages\anki\notes.py", line 67, in flush
AssertionError

**Comment by andrewsanchez** [comment]
You need to install `aab` into your Anki environment, e.g., `source ./pyenv/bin/activate && pip install aab`.  If you haven't set up a dev env successfully, which you can verify by running Anki via `./run`,  then I don't think installing `aab` will work and you should probably ask for help with running Anki from source on [the forum](https://forums.ankiweb.net/) or [Discord](https://discord.gg/Vd5zP6), and consult the [dev docs](https://github.com/ankitects/anki/blob/master/README.development).

However, it sounds to me like you might be better off packaging/sharing your add-on by following instructions here:  https://addon-docs.ankiweb.net/#/sharing

**Comment by PlEaSeH** [comment]
I just installed PyQt5 and it worked. I guess it didn't install when I was trying to do all the prerequisites.
