### ISSUE TITLE
Build doesn't get updated changes

### ISSUE THREAD

**Issue by warrenalphonso** [glutanimate/anki-addon-builder#16]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of `aab`
   - Tried pip version and installing from master branch
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

I've tried `aab build` on Mac and Ubuntu, but regardless of whatever changes I make to the source files, they don't seem to be reflected in the build. After I build and import the add-on into Anki via "Install from file...", the add-on works as if I hadn't made any changes. When I inspect the files in my `Anki2/addons21` folder that Anki is running, they are the "old" files. For example, I cloned review-heatmap and tried changing the `.ui` files or some Python logic, and none of my changes were reflected in the build. I also cloned an [exisitng PR to review-heatmap](https://github.com/glutanimate/review-heatmap/pull/62), merged it into my local `master` branch, and tried building; I still didn't see the new changes. I've got no idea what's going on.

**Comment by andrewsanchez** [comment]
Check out the documentation for `aab`'s positional argument, `version`:

```
$ aab build -h
usage: aab build [-h] [-t {anki21,anki20,all}] [-d {local,ankiweb,all}]
                 [version]

positional arguments:
  version               Version to build as a git reference (e.g. 'v1.2.0' or
                        'd338f6405'). Special keywords: 'current' – latest
                        commit, 'release' – latest tag. Leave empty to build
                        latest tag.
```

Commit your changes and then build your add-on to see those changes reflected in the build artifact.

**Comment by warrenalphonso** [comment]
Can't believe I missed that! Thanks for the quick response.
