### ISSUE TITLE
Find command failing on Windows

### ISSUE THREAD

**Issue by Undeadlol1** [glutanimate/anki-addon-builder#4]
When i am trying to build project locally there is an error:
```
Getting Git version info...

=== Build task 1/1 ===

--- Building Cloze Overlapper v0.4.0-alpha.0 for anki21/local ---

Cleaning repository...
File not found - '*.pyc'
Error while running command: 'find "."  \( -name '*.pyc' -o -name '*.pyo' -o -name '__pycache__' \) -delete'
```

![image](https://user-images.githubusercontent.com/4124323/59150382-fdf66e00-8a3b-11e9-9cdb-044443cd55bd.png)

Using PowerShell on Windows 10.

**Comment by glutanimate** [comment]
Hi Mihail.

[I've moved this issue to `aab` as it seems to be more appropriate here]

Concerning the first error: [As mentioned in the README](https://github.com/glutanimate/anki-addon-builder#platform-support), `aab` requires a POSIX environment like Linux or macOS to run.

Concerning the second:

Please note the lines in the build output

```
pyuic5 not found. Skipping pyuic build.
pyrcc5 not found. Skipping pyrcc build.
```

[As mentioned in the README](https://github.com/glutanimate/anki-addon-builder#requirements), you need to set up an Anki build environment, which includes these tools.

**Comment by Undeadlol1** [comment]
My apologies.

**Comment by Undeadlol1** [comment]
Thank you @glutanimate

**Comment by glutanimate** [comment]
No worries! Hope everything's working now :)
