### ISSUE TITLE
AAB Website Broken Link to Schema File

### ISSUE THREAD

**Issue by jeprecated** [glutanimate/anki-addon-builder#7]
https://pypi.org/project/aab/

>addon.json
>All of the metadata needed by aab to work correctly is stored in an addon.json file at the root of the project tree. For more information on its fields and their specifications please refer to the **schema file**.

This link is broken.

**Comment by glutanimate** [comment]
Thanks for letting me know! I updated the README link. Should be live with the next version update on PyPi.
